// E:\tornoinforma-landing\lib\lezione-slides.ts

export interface Slide {
  id: number
  tipo: 'intro' | 'contenuto' | 'lista' | 'citazione' | 'riepilogo' | 'esercizio'
  titolo: string
  sottotitolo?: string
  contenuto?: string
  punti?: string[]
  citazione?: string
  autore?: string
  emoji?: string
  highlight?: string
  audioNarrazione: string
}

export interface LezioneSlides {
  id: string
  titolo: string
  slides: Slide[]
}

export const lezioneSlidesData: Record<string, Slide[]> = {

  // ─────────────────────────────────────────────
  // MODULO 1 — Motivazione e Mentalità
  // ─────────────────────────────────────────────

  '1.1': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Trova il Tuo Vero Perché',
      sottotitolo: 'La motivazione profonda che non ti abbandona mai',
      emoji: '🔥',
      audioNarrazione: 'Benvenuto nella prima lezione del corso Torno in Forma. Oggi scoprirai il fondamento di tutto il tuo percorso: il tuo vero perché. Non la motivazione superficiale, ma quella profonda che ti fa alzare anche nei giorni difficili.',
    },
    {
      id: 2,
      tipo: 'contenuto',
      titolo: 'Perché la Motivazione Superficiale Non Basta',
      contenuto: 'La maggior parte delle persone inizia un percorso fitness con motivazioni esterne: "voglio sembrare bene in spiaggia", "voglio perdere 5 kg prima del matrimonio". Queste motivazioni si esauriscono in poche settimane.',
      emoji: '⚠️',
      audioNarrazione: 'Quante volte hai iniziato una dieta o una palestra con grande entusiasmo, per poi abbandonare dopo poche settimane? Il problema non sei tu. Il problema è che stavi usando la motivazione sbagliata. Le motivazioni esterne, legate all\'apparenza o a eventi temporanei, si consumano velocemente.',
    },
    {
      id: 3,
      tipo: 'lista',
      titolo: 'I 3 Livelli di Motivazione',
      punti: [
        '🔴 Livello 1 — Estetica: voglio sembrare meglio (dura 2-4 settimane)',
        '🟡 Livello 2 — Performance: voglio fare le scale senza fiatone (dura 2-3 mesi)',
        '🟢 Livello 3 — Identità: sono una persona sana e attiva (dura per sempre)',
      ],
      audioNarrazione: 'Esistono tre livelli di motivazione. Il primo livello è estetico: vuoi sembrare meglio. Dura qualche settimana. Il secondo livello è la performance: vuoi fare le scale senza fiatone, giocare con i tuoi figli. Dura qualche mese. Il terzo livello è identitario: sei una persona sana e attiva. Questo non finisce mai, perché è chi sei.',
    },
    {
      id: 4,
      tipo: 'esercizio',
      titolo: 'L\'Esercizio dei 5 Perché',
      contenuto: 'Prendi il tuo foglio di lavoro e scrivi la tua risposta alla domanda "Perché voglio mettermi in forma?" Poi chiediti 4 volte ancora "perché?". Al quinto perché troverai la tua vera motivazione.',
      emoji: '✍️',
      audioNarrazione: 'Apri il worksheet di questa lezione. Scrivi la risposta alla domanda: perché voglio mettermi in forma? Poi continua a chiedere "perché" per cinque volte. Questo esercizio, chiamato "i 5 Perché", è usato nelle più grandi aziende del mondo per trovare la causa radice di qualsiasi problema — o motivazione.',
    },
    {
      id: 5,
      tipo: 'citazione',
      titolo: '',
      citazione: 'Le persone non comprano cosa fai, comprano perché lo fai.',
      autore: 'Simon Sinek',
      audioNarrazione: 'Simon Sinek, uno dei più grandi esperti di leadership al mondo, ha detto: le persone non comprano cosa fai, comprano perché lo fai. Lo stesso vale per te. Non è il piano di allenamento che ti fa andare in palestra. È il tuo perché.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'La Tua Missione per Questa Settimana',
      punti: [
        '✅ Completa l\'esercizio dei 5 Perché nel worksheet',
        '✅ Scrivi il tuo "perché profondo" su un post-it e mettilo dove lo vedi ogni mattina',
        '✅ Condividi il tuo perché con una persona di fiducia',
      ],
      highlight: 'Il tuo perché è il carburante del tuo cambiamento',
      audioNarrazione: 'Per questa settimana hai tre compiti. Primo: completa l\'esercizio dei 5 Perché. Secondo: scrivi il tuo perché su un post-it e mettilo nello specchio del bagno o sul frigo. Terzo: dillo ad alta voce a qualcuno che ami. Quando lo condividi, diventa reale. Nella prossima lezione costruiremo il tuo piano d\'azione concreto.',
    },
  ],

  '1.2': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Obiettivi SMART e Piano d\'Azione',
      sottotitolo: 'Da sogno vago a piano concreto e misurabile',
      emoji: '🎯',
      audioNarrazione: 'Nella lezione precedente hai trovato il tuo vero perché. Oggi trasformiamo quella motivazione in obiettivi concreti e in un piano d\'azione pratico. Perché un sogno senza un piano è solo un desiderio.',
    },
    {
      id: 2,
      tipo: 'contenuto',
      titolo: 'Cos\'è un Obiettivo SMART',
      contenuto: 'SMART è un acronimo che definisce le caratteristiche di un obiettivo efficace. Un obiettivo vago come "voglio dimagrire" non attiva il cervello. Un obiettivo SMART sì.',
      emoji: '🧠',
      audioNarrazione: 'La maggior parte delle persone si fissa obiettivi vaghi: "voglio dimagrire", "voglio stare meglio". Il cervello non sa cosa fare con questi obiettivi. Ha bisogno di istruzioni precise. Il metodo SMART ti dà esattamente quello.',
    },
    {
      id: 3,
      tipo: 'lista',
      titolo: 'Il Metodo SMART',
      punti: [
        '📌 S — Specifico: "Perdo 8 kg" non "dimagrisco un po\'"',
        '📏 M — Misurabile: "Taglia 44" non "più snello"',
        '💪 A — Achievable: realistico per te, ora',
        '❤️ R — Rilevante: collegato al tuo perché profondo',
        '📅 T — Temporale: "entro il 30 giugno" non "presto"',
      ],
      audioNarrazione: 'SMART sta per: Specifico, Misurabile, Achievable cioè raggiungibile, Rilevante, e Temporale. Invece di "voglio dimagrire", un obiettivo SMART è: "Voglio perdere 8 kg entro il 30 giugno, passando dalla taglia 46 alla 44, per avere più energia con i miei figli." Senti la differenza? Il secondo attiva il cervello.',
    },
    {
      id: 4,
      tipo: 'esercizio',
      titolo: 'Costruisci il Tuo Obiettivo SMART',
      contenuto: 'Nel worksheet scrivi il tuo obiettivo principale rispettando tutti e 5 i criteri SMART. Poi suddividilo in 3 obiettivi intermedi mensili.',
      emoji: '✍️',
      audioNarrazione: 'Apri il worksheet e scrivi il tuo obiettivo SMART. Usa questa formula: "Voglio [cosa] entro [quando], passando da [punto A] a [punto B], per [il tuo perché]." Poi dividi questo obiettivo in tre tappe mensili. Questo trasforma un traguardo lontano in una serie di piccole vittorie vicine.',
    },
    {
      id: 5,
      tipo: 'contenuto',
      titolo: 'Il Piano delle 4 Aree',
      contenuto: 'Un piano completo copre 4 aree: Allenamento, Alimentazione, Recupero e Mentalità. Trascurare anche una sola area rallenta tutti i risultati.',
      emoji: '🗺️',
      highlight: 'Allenamento + Alimentazione + Recupero + Mentalità = Risultati',
      audioNarrazione: 'Un piano che funziona davvero copre quattro aree. L\'allenamento: cosa fai e quando. L\'alimentazione: cosa mangi e come. Il recupero: sonno e gestione dello stress. La mentalità: come gestisci gli ostacoli. Se trascuri anche una sola di queste aree, i risultati rallentano. Le tratteremo tutte nel corso.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'Il Tuo Piano Questa Settimana',
      punti: [
        '✅ Scrivi il tuo obiettivo SMART nel worksheet',
        '✅ Definisci 3 obiettivi intermedi mensili',
        '✅ Identifica la tua area più debole tra le 4',
      ],
      highlight: 'Un piano scritto aumenta del 42% la probabilità di raggiungere l\'obiettivo',
      audioNarrazione: 'Ricorda: chi scrive i propri obiettivi ha il 42% di probabilità in più di raggiungerli. Lo dice la ricerca della Dominican University. Quindi scrivi. Nella prossima lezione scopriremo come usare la scienza delle abitudini per rendere il tuo piano automatico.',
    },
  ],

  '1.3': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'La Scienza delle Abitudini',
      sottotitolo: 'Come costruire routine che si mantengono da sole',
      emoji: '🔄',
      audioNarrazione: 'Oggi entriamo nella neuroscienza delle abitudini. Perché non basta volerlo con forza di volontà — quella si esaurisce. Devi costruire abitudini automatiche che funzionano anche quando sei stanco, stressato o demotivato.',
    },
    {
      id: 2,
      tipo: 'contenuto',
      titolo: 'Il Loop dell\'Abitudine',
      contenuto: 'Ogni abitudine si compone di tre elementi: il Segnale (trigger), la Routine (l\'azione) e la Ricompensa. Capire questo loop ti permette di progettare abitudini che durano.',
      emoji: '🔬',
      audioNarrazione: 'Il neuroscienziato Charles Duhigg ha scoperto che ogni abitudine funziona secondo un loop a tre fasi. Il Segnale: qualcosa che innesca il comportamento. La Routine: il comportamento stesso. La Ricompensa: il beneficio che rinforza il loop. Per creare una nuova abitudine devi progettare consapevolmente questi tre elementi.',
    },
    {
      id: 3,
      tipo: 'lista',
      titolo: 'Progettare la Tua Abitudine Fitness',
      punti: [
        '🔔 Segnale: sveglia alle 6:30 oppure uscita dall\'ufficio alle 18:00',
        '🏃 Routine: 30 minuti di allenamento già programmato',
        '🎁 Ricompensa: doccia calda + podcast preferito + check ✅ sul calendario',
      ],
      audioNarrazione: 'Ecco come applicarlo all\'allenamento. Il tuo segnale potrebbe essere la sveglia alle 6:30 o l\'uscita dall\'ufficio. La routine è il tuo allenamento. La ricompensa deve essere immediata e piacevole: una doccia calda, il tuo podcast preferito, segnare il check sul calendario. Il cervello ama le ricompense immediate.',
    },
    {
      id: 4,
      tipo: 'contenuto',
      titolo: 'La Regola dei 2 Minuti',
      contenuto: 'James Clear insegna che ogni nuova abitudine deve iniziare con una versione che dura meno di 2 minuti. Non "vado in palestra 1 ora", ma "mi metto le scarpe da ginnastica". Il cervello non resiste a 2 minuti.',
      emoji: '⏱️',
      highlight: 'Inizia piccolo, diventa grande',
      audioNarrazione: 'James Clear, autore di Atomic Habits, ha sviluppato la Regola dei 2 Minuti. Qualsiasi nuova abitudine deve iniziare con una versione che duri meno di 2 minuti. Vuoi allenarti ogni giorno? L\'abitudine iniziale è: "mi metto le scarpe da ginnastica". Basta. Il cervello non resiste a 2 minuti, e spesso quei 2 minuti diventano 30.',
    },
    {
      id: 5,
      tipo: 'esercizio',
      titolo: 'Progetta le Tue 3 Abitudini Chiave',
      contenuto: 'Nel worksheet identifica le 3 abitudini più importanti per il tuo obiettivo. Per ognuna definisci: segnale specifico, routine e ricompensa immediata.',
      emoji: '✍️',
      audioNarrazione: 'Nel worksheet di questa lezione progetta le tue tre abitudini chiave. Per ognuna specifica: il segnale esatto, la routine e la ricompensa immediata. Esempio: Segnale: caffè del mattino. Routine: 10 minuti di stretching. Ricompensa: scrollare il telefono solo dopo. Più è specifico, più funziona.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'La Chiave del Cambiamento',
      punti: [
        '✅ Identifica il tuo loop: segnale, routine, ricompensa',
        '✅ Applica la regola dei 2 minuti alle tue abitudini',
        '✅ Non saltare mai due volte di fila — è la regola più importante',
      ],
      highlight: 'Non devi essere perfetto, devi essere consistente',
      audioNarrazione: 'Ricorda la regola più importante di tutte: non saltare mai due volte di fila. Perdere una volta è un incidente. Perdere due volte è l\'inizio di una nuova abitudine — quella sbagliata. Sii indulgente con te stesso, ma non lasciare che un giorno diventi due. Nella prossima lezione affronteremo gli ostacoli mentali che bloccano tutti.',
    },
  ],

  '1.4': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Superare gli Ostacoli Mentali',
      sottotitolo: 'Le trappole della mente che sabotano i tuoi risultati',
      emoji: '🧠',
      audioNarrazione: 'Questa è forse la lezione più importante del modulo. Puoi avere il miglior piano di allenamento del mondo, ma se la tua mente ti sabota, non arriverai da nessuna parte. Oggi identifichi i tuoi blocchi e impari a superarli.',
    },
    {
      id: 2,
      tipo: 'lista',
      titolo: 'I 5 Sabotatori Mentali Più Comuni',
      punti: [
        '😔 "Non ho tempo" — in realtà è "non è una priorità"',
        '😟 "Sono troppo stanco" — il movimento dà energia, non la toglie',
        '😰 "Ho già fallito in passato" — il passato non determina il futuro',
        '😤 "Non vedo risultati" — li stai cercando nel posto sbagliato',
        '😮 "Ho sbagliato tutto ieri" — un pasto non rovina nulla',
      ],
      audioNarrazione: 'Ecco i cinque sabotatori mentali che bloccano quasi tutti. "Non ho tempo" significa in realtà che non è ancora una priorità — e devi decidere se lo diventa. "Sono troppo stanco" è paradossale: il movimento aumenta l\'energia. "Ho già fallito" usa il passato per giustificare l\'inazione futura. "Non vedo risultati" spesso significa che li stai cercando sulla bilancia invece che nell\'energia e nel sonno. E "ho sbagliato ieri" cade nella trappola del tutto o niente.',
    },
    {
      id: 3,
      tipo: 'contenuto',
      titolo: 'Il Dialogo Interno: Come Cambiarlo',
      contenuto: 'Il tuo dialogo interno plasma la realtà. Non puoi controllare i pensieri che arrivano, ma puoi scegliere quelli a cui rispondere. La tecnica del "reframe" trasforma ogni sabotatore in una risorsa.',
      emoji: '💬',
      audioNarrazione: 'Il dialogo interno — quella voce nella testa — è il tuo allenatore più influente. Se ti dice continuamente che non ce la fai, non ce la farai. La buona notizia è che puoi riaddestrare quella voce. Si chiama reframe cognitivo: trasformi ogni pensiero limitante in una domanda che apre possibilità.',
    },
    {
      id: 4,
      tipo: 'lista',
      titolo: 'La Tecnica del Reframe',
      punti: [
        '❌ "Non ho tempo" → ✅ "Come posso ricavare 20 minuti oggi?"',
        '❌ "Sono troppo stanco" → ✅ "Cosa posso fare anche con poca energia?"',
        '❌ "Ho già fallito" → ✅ "Cosa ho imparato che posso usare adesso?"',
        '❌ "Non vedo risultati" → ✅ "Quali progressi non ho ancora notato?"',
      ],
      audioNarrazione: 'Ecco il reframe in azione. "Non ho tempo" diventa "Come posso ricavare 20 minuti oggi?" Il cervello smette di giustificare e inizia a trovare soluzioni. "Sono troppo stanco" diventa "Cosa posso fare anche con poca energia?" Magari una camminata di 15 minuti invece della palestra. La domanda apre porte che l\'affermazione negativa chiude.',
    },
    {
      id: 5,
      tipo: 'citazione',
      titolo: '',
      citazione: 'Non è quello che ti succede che conta, ma come rispondi a quello che ti succede.',
      autore: 'Epitteto',
      audioNarrazione: 'Il filosofo stoico Epitteto lo diceva duemila anni fa: non è quello che ti succede che conta, ma come rispondi. Non puoi controllare se piove, se sei stanco, se hai un imprevisto. Puoi sempre controllare la tua risposta.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'Complimenti per il Modulo 1!',
      punti: [
        '✅ Hai trovato il tuo vero perché',
        '✅ Hai costruito il tuo obiettivo SMART',
        '✅ Hai progettato le tue abitudini chiave',
        '✅ Hai identificato i tuoi sabotatori e come superarli',
      ],
      highlight: 'Sei pronto per il Modulo 2: Alimentazione per il Successo',
      audioNarrazione: 'Complimenti! Hai completato il Modulo 1 — Motivazione e Mentalità. Hai trovato il tuo perché profondo, costruito obiettivi SMART, progettato abitudini con il metodo scientifico e imparato a superare i tuoi sabotatori mentali. Ora hai le fondamenta. Nel Modulo 2 costruiremo la tua strategia nutrizionale. A presto!',
    },
  ],

  // ─────────────────────────────────────────────
  // MODULO 2 — Alimentazione per il Successo
  // ─────────────────────────────────────────────

  '2.1': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Le Basi della Nutrizione',
      sottotitolo: 'Tutto quello che devi sapere senza diventare un dietologo',
      emoji: '🥗',
      audioNarrazione: 'Benvenuto nel Modulo 2. Dimentica le diete restrittive e le regole assurde. Oggi impariamo le basi della nutrizione in modo pratico: cosa mangiare, quanto, e soprattutto perché. Senza privazioni, senza stress.',
    },
    {
      id: 2,
      tipo: 'contenuto',
      titolo: 'Le Calorie: Amiche o Nemiche?',
      contenuto: 'Le calorie sono semplicemente unità di energia. Non sono né buone né cattive. Quello che conta è il bilancio: se consumi più di quello che bruci, ingrassi. Se consumi meno, dimagrisci. Ma non tutte le calorie sono uguali.',
      emoji: '⚡',
      audioNarrazione: 'Le calorie hanno una pessima reputazione, ma sono semplicemente unità di misura dell\'energia. Come i chilometri per la distanza. Il principio base è semplice: se mangi più calorie di quelle che bruci, il tuo corpo le immagazzina come grasso. Se ne mangi meno, attinge alle riserve. Detto questo, 100 calorie di pollo non hanno lo stesso effetto di 100 calorie di zucchero.',
    },
    {
      id: 3,
      tipo: 'contenuto',
      titolo: 'Calcola il Tuo Fabbisogno Calorico',
      contenuto: 'Il tuo fabbisogno dipende dal metabolismo basale (BMR) moltiplicato per il livello di attività. Formula di Mifflin-St Jeor:\n• Uomini: (10 × kg) + (6.25 × cm) - (5 × anni) + 5\n• Donne: (10 × kg) + (6.25 × cm) - (5 × anni) - 161',
      emoji: '🧮',
      highlight: 'Il tuo BMR × fattore attività = calorie di mantenimento',
      audioNarrazione: 'Per calcolare le tue calorie di mantenimento usi la formula di Mifflin-St Jeor. Per gli uomini: dieci per il peso in chili, più sei virgola venticinque per l\'altezza in centimetri, meno cinque per l\'età, più cinque. Per le donne uguale ma meno 161 alla fine. Poi moltiplichi per il fattore attività: 1.2 se sei sedentario, 1.375 leggero, 1.55 moderato, 1.725 molto attivo.',
    },
    {
      id: 4,
      tipo: 'lista',
      titolo: 'I Fattori di Attività',
      punti: [
        '🛋️ Sedentario (×1.2) — lavoro da scrivania, poca attività',
        '🚶 Leggero (×1.375) — 1-3 allenamenti a settimana',
        '🏃 Moderato (×1.55) — 3-5 allenamenti a settimana',
        '💪 Molto attivo (×1.725) — 6-7 allenamenti o lavoro fisico',
      ],
      audioNarrazione: 'Ecco i quattro fattori di attività. Sedentario, moltiplica per 1.2. Leggero — uno o tre allenamenti a settimana — per 1.375. Moderato — tre o cinque allenamenti — per 1.55. Molto attivo — sei o sette allenamenti o lavoro fisico — per 1.725. Il risultato è il tuo TDEE, cioè il fabbisogno calorico giornaliero totale.',
    },
    {
      id: 5,
      tipo: 'esercizio',
      titolo: 'Calcola le Tue Calorie',
      contenuto: 'Nel worksheet calcola il tuo BMR con la formula di Mifflin-St Jeor e poi il tuo TDEE moltiplicando per il fattore di attività corretto. Questo è il tuo punto di partenza.',
      emoji: '✍️',
      audioNarrazione: 'Nel worksheet di questa lezione trovi la tabella per calcolare il tuo BMR e TDEE passo per passo. Fallo adesso. Questo numero è fondamentale perché tutto il piano nutrizionale si costruisce da qui. Per perdere peso sottrai 300-500 calorie al giorno. Per aumentare la massa muscolare aggiungi 200-300 calorie.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'Hai le Fondamenta Nutrizionali',
      punti: [
        '✅ Conosci il tuo BMR e TDEE',
        '✅ Sai come calcolare il deficit calorico per dimagrire',
        '✅ Capisci perché non tutte le calorie sono uguali',
      ],
      highlight: 'Nella prossima lezione: macronutrienti — cosa mangiare davvero',
      audioNarrazione: 'Ottimo lavoro. Ora sai come funziona il tuo metabolismo e hai calcolato il tuo fabbisogno calorico personale. Nella prossima lezione entriamo nei macronutrienti: proteine, carboidrati e grassi. Scoprirai quanto di ognuno mangiare in base al tuo obiettivo specifico.',
    },
  ],

  '2.2': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Macronutrienti: Cosa Mangiare e Perché',
      sottotitolo: 'Proteine, carboidrati e grassi: il trio che trasforma il tuo corpo',
      emoji: '🥩',
      audioNarrazione: 'Oggi parliamo di macronutrienti. Dimentica la guerra ai carboidrati o ai grassi. Il tuo corpo ha bisogno di tutti e tre. La chiave è la proporzione giusta in base al tuo obiettivo. Partiamo dalle proteine, le più importanti.',
    },
    {
      id: 2,
      tipo: 'contenuto',
      titolo: 'Le Proteine: Il Mattone del Tuo Corpo',
      contenuto: 'Le proteine costruiscono e riparano i muscoli, mantengono il senso di sazietà e bruciano più calorie durante la digestione rispetto agli altri macros. Obiettivo: 1.6-2.2g per kg di peso corporeo.',
      emoji: '💪',
      highlight: '1.6-2.2g di proteine per kg di peso',
      audioNarrazione: 'Le proteine sono il mattone del tuo corpo. Costruiscono e riparano i muscoli, ti tengono sazio più a lungo e hanno l\'effetto termico più alto: il corpo brucia il 20-30% delle calorie delle proteine solo per digerirle. L\'obiettivo per chi si allena è tra 1.6 e 2.2 grammi per chilo di peso corporeo. Per una persona di 70 kg, sono dai 112 ai 154 grammi al giorno.',
    },
    {
      id: 3,
      tipo: 'lista',
      titolo: 'Fonti Proteiche Ottimali',
      punti: [
        '🐔 Carni magre: pollo, tacchino, vitello (26-30g/100g)',
        '🐟 Pesce: tonno, salmone, merluzzo (20-25g/100g)',
        '🥚 Uova: 6g per uovo, fonte completa di aminoacidi',
        '🫘 Legumi: lenticchie, ceci, fagioli (7-9g/100g cotti)',
        '🧀 Latticini magri: ricotta, yogurt greco, fiocchi di latte',
      ],
      audioNarrazione: 'Le migliori fonti proteiche sono le carni magre come pollo e tacchino, con circa 28-30 grammi per 100 grammi. Il pesce, in particolare tonno e salmone. Le uova, una delle fonti proteiche più complete esistenti. I legumi, ottimi per chi preferisce ridurre le proteine animali. E i latticini magri come yogurt greco e ricotta.',
    },
    {
      id: 4,
      tipo: 'contenuto',
      titolo: 'Carboidrati e Grassi: La Verità',
      contenuto: 'I carboidrati sono il carburante principale per l\'allenamento: 3-5g/kg nei giorni di allenamento. I grassi sono essenziali per ormoni e cervello: 0.8-1.2g/kg al giorno. Zero non è un\'opzione.',
      emoji: '🍚',
      audioNarrazione: 'I carboidrati non fanno ingrassare — l\'eccesso calorico sì. I carbs sono il carburante preferito del cervello e dei muscoli durante l\'esercizio intenso. Nei giorni di allenamento mira a 3-5 grammi per chilo. I grassi invece vengono spesso demonizzati, ma sono essenziali per la produzione ormonale, l\'assorbimento di vitamine e la salute cerebrale. Mira a 0.8-1.2 grammi per chilo.',
    },
    {
      id: 5,
      tipo: 'lista',
      titolo: 'Il Piatto Perfetto',
      punti: [
        '🥦 ½ piatto di verdure non amidacee (fibra, micronutrienti)',
        '🍗 ¼ piatto di proteine magre (150-200g cotti)',
        '🍚 ¼ piatto di carboidrati complessi (riso, pasta integrale, patate)',
        '🫒 1-2 cucchiai di olio extravergine d\'oliva (grassi buoni)',
      ],
      audioNarrazione: 'Ecco la struttura del piatto perfetto. Metà piatto di verdure non amidacee: fibre, vitamine, minerali. Un quarto di proteine magre, circa 150-200 grammi. Un quarto di carboidrati complessi: riso integrale, pasta integrale, patate dolci. E uno o due cucchiai di olio extravergine d\'oliva. Semplice, equilibrato, sostenibile.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'I Tuoi Macro Personali',
      punti: [
        '✅ Calcola le tue proteine: peso × 1.8-2g = grammi al giorno',
        '✅ I carbs variano in base ai giorni di allenamento',
        '✅ I grassi non vanno mai eliminati, solo scelti bene',
      ],
      highlight: 'Usa il worksheet per calcolare i tuoi macro personali',
      audioNarrazione: 'Nel worksheet di questa lezione trovi la tabella per calcolare i tuoi macro personalizzati. Inserisci il tuo peso e obiettivo e avrai proteine, carboidrati e grassi al giorno. Nella prossima lezione vedremo come tradurre questi numeri in pasti concreti e sostenibili nella vita di tutti i giorni.',
    },
  ],

  '2.3': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Costruire un Piano Alimentare Sostenibile',
      sottotitolo: 'Dal calcolo dei macro a pasti reali che ami mangiare',
      emoji: '📋',
      audioNarrazione: 'Hai i tuoi macro, hai le calorie. Ora costruiamo il piano alimentare che funziona nella tua vita reale. Non una dieta da rivista, ma un sistema che riesci a seguire anche nelle settimane difficili.',
    },
    {
      id: 2,
      tipo: 'contenuto',
      titolo: 'La Struttura dei Pasti',
      contenuto: 'Non esiste il numero di pasti "magico". Che siano 3 o 5 al giorno, conta il totale. Detto questo, 3-4 pasti ben strutturati con almeno 25-30g di proteine per pasto ottimizzano la sintesi proteica muscolare.',
      emoji: '🕐',
      audioNarrazione: 'Uno dei miti più diffusi è che bisogna mangiare ogni 2-3 ore per "tenere alto il metabolismo". La ricerca non lo supporta. Quello che conta è il totale calorico e proteico della giornata. Detto questo, distribuire le proteine in 3-4 pasti da almeno 25-30 grammi ciascuno ottimizza la costruzione muscolare.',
    },
    {
      id: 3,
      tipo: 'lista',
      titolo: 'Schema Pasti Tipo (3 Pasti + 1 Spuntino)',
      punti: [
        '🌅 Colazione: proteine + carbs + grassi buoni (es. uova + pane integrale + avocado)',
        '☀️ Pranzo: il piatto perfetto (proteine + verdure + carbs)',
        '🍎 Spuntino: yogurt greco + frutta o ricotta + frutta secca',
        '🌙 Cena: proteine + verdure + carbs moderati (o niente se è tardi)',
      ],
      audioNarrazione: 'Ecco uno schema pratico a tre pasti e uno spuntino. Colazione: uova strapazzate, pane integrale e avocado. Pranzo: il piatto perfetto che abbiamo visto prima. Spuntino: yogurt greco con frutta o ricotta con frutta secca. Cena: proteine e verdure con carboidrati moderati, soprattutto se mangi tardi.',
    },
    {
      id: 4,
      tipo: 'contenuto',
      titolo: 'Il Meal Prep della Domenica',
      contenuto: 'Dedicare 1-2 ore la domenica a preparare il cibo della settimana è la singola abitudine che fa più differenza. Cucina in batch: 500-600g di proteine, una pentola di cereali, verdure lavate e tagliate.',
      emoji: '👨‍🍳',
      highlight: '2 ore domenica = settimana di scelte facili',
      audioNarrazione: 'Il meal prep settimanale è il segreto dei professionisti del fitness. Dedica 90-120 minuti la domenica. Cuoci 500-600 grammi di petto di pollo o tacchino. Prepara una pentola di riso integrale o pasta. Lava e taglia le verdure. Metti tutto in contenitori separati. In questo modo ogni pasto della settimana diventa un assemblaggio di 5 minuti.',
    },
    {
      id: 5,
      tipo: 'lista',
      titolo: 'I Cibi da Avere Sempre in Casa',
      punti: [
        '🥚 Uova (versatili, economiche, complete)',
        '🐔 Pollo e tacchino surgelati',
        '🫘 Legumi in scatola (lenticchie, ceci)',
        '🌾 Avena, riso integrale, pasta di legumi',
        '🥬 Verdure surgelate (pratiche, stessa qualità)',
        '🫒 Olio EVO, noci, mandorle',
      ],
      audioNarrazione: 'Questi sono i cibi che non devono mai mancare nella tua dispensa. Uova: veloci, economiche, proteiche. Pollo e tacchino surgelati: sempre pronti quando non hai tempo di fare la spesa. Legumi in scatola: ceci e lenticchie si scaldano in 5 minuti. Cereali integrali: avena per colazione, riso o pasta per i pasti. Verdure surgelate: stessa qualità nutrizionale di quelle fresche.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'Il Tuo Piano Questa Settimana',
      punti: [
        '✅ Progetta i tuoi pasti tipo nel worksheet',
        '✅ Fai la spesa con la lista dei cibi base',
        '✅ Prova il meal prep domenicale almeno una volta',
      ],
      highlight: 'La prossima lezione: come gestire pasti fuori e imprevisti senza rovinare tutto',
      audioNarrazione: 'Questa settimana hai tre compiti. Progetta i tuoi tre pasti tipo. Fai la spesa con la lista dei cibi base. E prova il meal prep domenicale — basta una volta per capire quanto cambia la vita. Nella prossima lezione affrontiamo la situazione che mette in crisi tutti: i pasti fuori casa e gli imprevisti.',
    },
  ],

  '2.4': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Gestire Pasti Fuori e Imprevisti',
      sottotitolo: 'Come mangiare bene anche quando non controlli il menù',
      emoji: '🍽️',
      audioNarrazione: 'Sai già come mangiare a casa. Ma la vita reale è fatta di pranzi di lavoro, cene con amici, feste di compleanno e viaggi. Oggi impari a navigare queste situazioni senza stress e senza vanificare il tuo progresso.',
    },
    {
      id: 2,
      tipo: 'contenuto',
      titolo: 'La Regola 80/20',
      contenuto: 'L\'80% dei tuoi pasti è strutturato e allineato ai tuoi obiettivi. Il 20% è flessibile — cene fuori, pizze, aperitivi. Su 21 pasti settimanali: 17 sono "bilanciati", 4 sono liberi.',
      emoji: '⚖️',
      highlight: '17 pasti bilanciati + 4 flessibili = libertà sostenibile',
      audioNarrazione: 'La regola 80-20 è la strategia nutrizionale più sostenibile che esista. Ottanta per cento dei tuoi pasti — circa 17 su 21 a settimana — sono strutturati e allineati ai tuoi obiettivi. Il venti per cento, circa 4 pasti, sono completamente liberi. Questo significa che puoi avere due cene a settimana dove mangi quello che vuoi senza sensi di colpa. La pizza del sabato non rovina il martedì.',
    },
    {
      id: 3,
      tipo: 'lista',
      titolo: 'Strategie per il Ristorante',
      punti: [
        '🥗 Inizia con un\'insalata o antipasto leggero (sazi prima)',
        '🍗 Scegli secondi alla griglia o al vapore',
        '🍷 Mantieni i carboidrati (pane, pasta) ma dimezza la porzione',
        '💧 Bevi acqua tra un sorso di vino e l\'altro',
        '🚫 Evita il cestino del pane prima che arrivi il cibo',
      ],
      audioNarrazione: 'Ecco le strategie pratiche al ristorante. Prima: ordina un\'insalata o un antipasto leggero — sazi e mangi meno nel secondo. Seconda: preferisci secondi alla griglia o al vapore. Terza: non eliminare i carbs, ma dimezza la porzione di pane o pasta. Quarta: bevi acqua tra un sorso di vino e l\'altro. Quinta: evita il cestino del pane mentre aspetti — sono calorie automatiche.',
    },
    {
      id: 4,
      tipo: 'contenuto',
      titolo: 'Gestire Viaggi e Trasferte',
      contenuto: 'In viaggio la sfida è reale. La strategia è: controlli le variabili che puoi controllare. Colazione proteica, movimento minimo quotidiano, idratazione abbondante. Il resto è flessibile.',
      emoji: '✈️',
      audioNarrazione: 'In viaggio perdi il controllo su molte variabili. Accettalo. Concentrati su quelle che puoi controllare. Inizia ogni giornata con una colazione proteica — uova scrambled in quasi tutti gli hotel. Fai almeno 8000 passi al giorno — esplori la città invece di prendere il taxi. Bevi almeno 2 litri d\'acqua. Il resto — cene, pranzi di lavoro — lascia che siano flessibili.',
    },
    {
      id: 5,
      tipo: 'lista',
      titolo: 'La Strategia del Giorno Dopo',
      punti: [
        '✅ Non digiunare il giorno dopo — aumenta il cortisolo e il craving',
        '✅ Aumenta l\'idratazione (il sale ritiene liquidi)',
        '✅ Fai una sessione di movimento leggero o camminata',
        '✅ Torna al tuo piano normale dal pasto successivo',
        '🚫 Non "compensare" saltando pasti — crea un ciclo negativo',
      ],
      audioNarrazione: 'La mattina dopo un pasto abbondante, molte persone saltano la colazione per compensare. Errore. Digiunare aumenta il cortisolo e i craving, portandoti a mangiare ancora di più nel corso della giornata. Invece: idratati abbondantemente, mangia una colazione proteica normale, fai una camminata e riprendi il tuo piano dal pasto successivo. Punto. Nessun dramma.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'Complimenti per il Modulo 2!',
      punti: [
        '✅ Conosci il tuo fabbisogno calorico e i tuoi macro',
        '✅ Sai costruire pasti equilibrati con il piatto perfetto',
        '✅ Hai strategie per ristoranti, viaggi e feste',
        '✅ La regola 80/20 è la tua bussola nutrizionale',
      ],
      highlight: 'Pronto per il Modulo 3: Il Piano di Allenamento',
      audioNarrazione: 'Hai completato il Modulo 2 sull\'alimentazione. Ora hai un sistema nutrizionale completo e flessibile che funziona nella vita reale. Nel Modulo 3 costruiremo il tuo piano di allenamento personalizzato. Cardio, forza, flessibilità e recupero. A presto!',
    },
  ],

  // ─────────────────────────────────────────────
  // MODULO 3 — Il Piano di Allenamento
  // ─────────────────────────────────────────────

  '3.1': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Scegliere l\'Allenamento in Base agli Obiettivi',
      sottotitolo: 'Il piano giusto per te, non per qualcun altro',
      emoji: '🏋️',
      audioNarrazione: 'Benvenuto nel Modulo 3. Oggi costruiamo il tuo piano di allenamento personalizzato. Perché quello che funziona per il tuo collega o per la tua migliore amica potrebbe non funzionare per te. Il piano migliore è quello che si adatta al tuo obiettivo, al tuo livello e alla tua vita.',
    },
    {
      id: 2,
      tipo: 'lista',
      titolo: 'I 4 Pilastri dell\'Allenamento Completo',
      punti: [
        '❤️ Cardio — salute cardiovascolare, brucia grassi',
        '💪 Forza — muscoli, metabolismo, postura',
        '🤸 Flessibilità/Mobilità — prevenzione infortuni, qualità del movimento',
        '😴 Recupero — senza questo, gli altri tre non funzionano',
      ],
      audioNarrazione: 'Un piano di allenamento completo si regge su quattro pilastri. Il cardio per la salute del cuore e il bruciare grassi. La forza per costruire muscoli, accelerare il metabolismo e migliorare la postura. La flessibilità e mobilità per muoversi bene e prevenire infortuni. E il recupero — spesso il più trascurato — senza cui gli altri tre perdono efficacia.',
    },
    {
      id: 3,
      tipo: 'contenuto',
      titolo: 'Quale Obiettivo Hai?',
      contenuto: 'Dimagrire: cardio + forza + deficit calorico. Tonificarsi: forza + cardio moderato + mantenimento calorico. Aumentare la massa: forza progressiva + surplus calorico. Migliorare la salute: tutti e quattro i pilastri in equilibrio.',
      emoji: '🎯',
      audioNarrazione: 'La scelta del piano dipende dal tuo obiettivo principale. Per dimagrire: combinazione di forza e cardio con deficit calorico. Contrariamente a quello che si pensa, la forza brucia più grasso del solo cardio nel lungo periodo. Per tonificarsi: forza come priorità con cardio moderato. Per aumentare la massa: forza progressiva con leggero surplus calorico. Per migliorare la salute generale: tutti e quattro i pilastri in equilibrio.',
    },
    {
      id: 4,
      tipo: 'lista',
      titolo: 'Quante Sessioni a Settimana?',
      punti: [
        '🟢 Principiante: 2-3 sessioni (full body)',
        '🟡 Intermedio: 3-4 sessioni (split upper/lower)',
        '🔴 Avanzato: 4-5 sessioni (split per gruppi muscolari)',
        '⚠️ Più non significa meglio — il recupero è parte dell\'allenamento',
      ],
      audioNarrazione: 'Quante sessioni a settimana? Come principiante, 2-3 sessioni full body sono più che sufficienti. Come intermedio, 3-4 sessioni con uno split tra parte alta e bassa. Come avanzato, 4-5 sessioni con split più specifici per gruppi muscolari. Ricorda: più non significa sempre meglio. Il recupero è parte integrante dell\'allenamento, non il suo contrario.',
    },
    {
      id: 5,
      tipo: 'contenuto',
      titolo: 'Casa, Palestra o Outdoor?',
      contenuto: 'Non hai bisogno di una palestra per trasformare il corpo. Gli esercizi a corpo libero, i pesi leggeri e le attività outdoor sono efficaci quanto i macchinari se eseguiti con consistenza e progressione.',
      emoji: '🌳',
      audioNarrazione: 'Non hai scuse: puoi allenarti ovunque. A casa con il corpo libero e qualche elastico, in palestra con pesi e macchinari, o all\'aperto con corsa, bici e calisthenics. La differenza non è il luogo, è la consistenza. Un allenamento a casa tre volte a settimana batte una palestra costosa che usi una volta al mese.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'Scegli il Tuo Piano',
      punti: [
        '✅ Identifica il tuo obiettivo principale',
        '✅ Decidi quante sessioni puoi fare realisticamente',
        '✅ Scegli il tuo ambiente preferito (casa/palestra/outdoor)',
      ],
      highlight: 'Nella prossima lezione: i fondamentali di cardio, forza e flessibilità',
      audioNarrazione: 'Ora sai come scegliere il piano giusto per te. Nella prossima lezione entriamo nel dettaglio: come fare cardio in modo efficace, come impostare l\'allenamento di forza con la progressione corretta, e perché la flessibilità non è opzionale. A presto!',
    },
  ],

  '3.2': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Cardio, Forza e Flessibilità: i Fondamentali',
      sottotitolo: 'Come fare ogni tipo di allenamento nel modo giusto',
      emoji: '🏃',
      audioNarrazione: 'Oggi entriamo nel vivo. Cardio: LISS o HIIT? Forza: quante serie e ripetizioni? Flessibilità: stretching statico o dinamico? Rispondo a tutte queste domande con la scienza, non con l\'opinione.',
    },
    {
      id: 2,
      tipo: 'lista',
      titolo: 'Cardio: LISS vs HIIT',
      punti: [
        '🐢 LISS (Low Intensity Steady State): 30-60 min, 50-65% FCmax, brucia grassi, recupero rapido',
        '⚡ HIIT (High Intensity Interval Training): 15-25 min, 85-95% FCmax, effetto afterburn, 48h recupero',
        '✅ Consigliato: 2 LISS + 1 HIIT a settimana per principianti',
        '✅ Cardio migliore: quello che fai davvero e che ti piace',
      ],
      audioNarrazione: 'Il LISS, cardio a bassa intensità costante, è la corsa tranquilla, la bici, il nuoto lento. Durata 30-60 minuti, frequenza cardiaca al 50-65% del massimo. Brucia prevalentemente grassi durante la sessione ed è easy da recuperare. L\'HIIT è l\'opposto: 15-25 minuti di alternanza tra sprint e recupero. Più intenso, crea l\'effetto afterburn — bruci calorie per ore dopo. Ma richiede 48 ore di recupero. Per iniziare: due LISS e un HIIT a settimana.',
    },
    {
      id: 3,
      tipo: 'contenuto',
      titolo: 'Forza: La Formula delle Serie e Ripetizioni',
      contenuto: 'L\'obiettivo cambia la formula:\n• Forza massimale: 3-5 serie × 3-5 rip, carichi pesanti\n• Ipertrofia (massa): 3-4 serie × 8-12 rip, carichi medi\n• Tonificazione/Resistenza: 2-3 serie × 15-20 rip, carichi leggeri',
      emoji: '🏋️',
      highlight: 'La progressione nel tempo è la variabile più importante',
      audioNarrazione: 'Per la forza massimale: 3-5 serie da 3-5 ripetizioni con carichi elevati e lunghi recuperi. Per l\'ipertrofia, cioè aumentare il volume muscolare: 3-4 serie da 8-12 ripetizioni con carichi medi. Per la tonificazione e la resistenza muscolare: 2-3 serie da 15-20 ripetizioni con carichi leggeri. Ma ricorda: la cosa più importante non è la formula specifica, è la progressione. Devi aumentare il carico o le rip nel tempo.',
    },
    {
      id: 4,
      tipo: 'lista',
      titolo: 'I 5 Esercizi Fondamentali',
      punti: [
        '🏋️ Squat — il re degli esercizi per gambe e core',
        '🤸 Stacco da terra — forza totale, postura, schiena',
        '💪 Panca piana — petto, spalle, tricipiti',
        '🙆 Trazioni/Lat machine — schiena, bicipiti, postura',
        '⬆️ Military press — spalle, tricipiti, stabilità',
      ],
      audioNarrazione: 'Se potessi scegliere solo cinque esercizi per tutta la vita, sarebbero questi. Squat: lavora gambe, glutei e core in un unico movimento. Stacco da terra: la catena posteriore completa. Panca piana: tutta la parte superiore anteriore. Trazioni o lat machine: schiena e bicipiti. E military press per le spalle. Questi cinque movimenti, eseguiti bene e con progressione, costruiscono un fisico completo.',
    },
    {
      id: 5,
      tipo: 'contenuto',
      titolo: 'Flessibilità: Non È Opzionale',
      contenuto: 'Lo stretching non è il cool-down opzionale da saltare. Migliora la postura, previene infortuni, riduce il dolore muscolare e migliora la qualità del movimento. 10 minuti al giorno fanno la differenza.',
      emoji: '🤸',
      audioNarrazione: 'Lo stretching è la parte più trascurata di qualsiasi programma. Eppure è quella che nel lungo periodo fa più differenza sulla qualità della vita. Non parlo di diventare ginnasta. Parlo di 10 minuti al giorno di mobilità articolare e stretching dei principali gruppi muscolari. Migliora la postura, riduce il mal di schiena, previene infortuni e ti fa muovere meglio nella vita quotidiana.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'Hai gli Strumenti per Allenarti Bene',
      punti: [
        '✅ Sai la differenza tra LISS e HIIT e quando usarli',
        '✅ Conosci la formula serie/ripetizioni per il tuo obiettivo',
        '✅ Hai i 5 esercizi fondamentali',
        '✅ Hai capito perché la flessibilità non va saltata',
      ],
      highlight: 'Nella prossima lezione: le schede di allenamento pratiche pronte all\'uso',
      audioNarrazione: 'Ottimo! Ora hai la teoria completa sull\'allenamento. Nella prossima lezione ti do le schede pratiche pronte da usare: dalla scheda A per principianti full body alla scheda D per chi vuole aumentare la massa muscolare. Sceglierai quella che si adatta al tuo obiettivo e alla tua disponibilità.',
    },
  ],

  '3.3': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Le Schede di Allenamento Pratiche',
      sottotitolo: '5 schede pronte all\'uso per ogni obiettivo e livello',
      emoji: '📋',
      audioNarrazione: 'Oggi ti consegno il tuo piano di allenamento concreto. Ho preparato 5 schede per obiettivi e livelli diversi. Sceglierai quella che si adatta meglio a te — o la combinerai con il tuo personal trainer. Tutto è nel worksheet.',
    },
    {
      id: 2,
      tipo: 'lista',
      titolo: 'Le 5 Schede Disponibili',
      punti: [
        '🅐 Scheda A — Full Body Principiante (2-3 gg/sett)',
        '🅑 Scheda B — Tonificazione Donna (3 gg/sett)',
        '🅒 Scheda C — Dimagrimento Intensivo (4 gg/sett)',
        '🅓 Scheda D — Massa Muscolare Split (4-5 gg/sett)',
        '🅔 Scheda E — Movimento Over 60 (2-3 gg/sett)',
      ],
      audioNarrazione: 'Le cinque schede coprono tutti i principali obiettivi. La Scheda A è per chi inizia da zero: full body, 2-3 giorni a settimana. La B è pensata per la tonificazione femminile con 3 giorni. La C per chi vuole dimagrire in modo intensivo con 4 giorni. La D per chi vuole aumentare la massa muscolare con uno split su 4-5 giorni. E la E per chi ha più di 60 anni, con focus su mobilità, equilibrio e forza funzionale.',
    },
    {
      id: 3,
      tipo: 'contenuto',
      titolo: 'Scheda A — Full Body Principiante',
      contenuto: 'Lunedì/Mercoledì/Venerdì:\n• Squat 3×12\n• Push-up 3×10\n• Rematore con manubrio 3×12\n• Affondi 3×10 per gamba\n• Plank 3×30 sec\n• Cardio 15-20 min LISS',
      emoji: '🅐',
      audioNarrazione: 'La Scheda A si allena tre giorni a settimana: lunedì, mercoledì e venerdì. Ogni sessione: squat 3 serie da 12 ripetizioni, push-up 3 serie da 10, rematore con manubrio 3 serie da 12, affondi 3 serie da 10 per gamba, plank 3 volte da 30 secondi. Chiudi con 15-20 minuti di cardio leggero. Durata totale: circa 45-50 minuti.',
    },
    {
      id: 4,
      tipo: 'contenuto',
      titolo: 'Scheda C — Dimagrimento Intensivo',
      contenuto: 'Lun: Parte superiore + HIIT 15 min\nMar: Gambe + glutei + LISS 20 min\nGio: Full body circuito + HIIT 15 min\nVen: Cardio + core + LISS 30 min',
      emoji: '🅒',
      audioNarrazione: 'La Scheda C per il dimagrimento combina forza e cardio in 4 giorni. Lunedì: parte superiore più HIIT da 15 minuti. Martedì: gambe e glutei più LISS da 20 minuti. Giovedì: full body a circuito più un altro HIIT. Venerdì: cardio prolungato con core e stretching. Questa scheda massimizza la spesa calorica settimanale mantenendo la massa muscolare.',
    },
    {
      id: 5,
      tipo: 'contenuto',
      titolo: 'Scheda E — Movimento Over 60',
      contenuto: 'Priorità: equilibrio, mobilità, forza funzionale.\n• Chair squat 2×10\n• Camminata 30 min\n• Stretching completo 15 min\n• Esercizi equilibrio monopodalico\n• Respiro diaframmatico',
      emoji: '🅔',
      audioNarrazione: 'La Scheda E è progettata per chi ha più di 60 anni e vuole mantenersi in movimento in sicurezza. Le priorità sono tre: equilibrio, per prevenire le cadute. Mobilità articolare, per mantenere l\'autonomia nei movimenti quotidiani. Forza funzionale, per alzarsi dalla sedia, fare le scale, portare la spesa. Sessioni da 40-45 minuti, 2-3 volte a settimana.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'La Tua Scheda è nel Worksheet',
      punti: [
        '✅ Scegli la scheda in base al tuo obiettivo',
        '✅ Scarica il PDF con tutte le schede nel dettaglio',
        '✅ Segna gli allenamenti sul calendario ora',
      ],
      highlight: 'Un allenamento pianificato ha 3× più probabilità di essere eseguito',
      audioNarrazione: 'Nel worksheet di questa lezione trovi tutte e cinque le schede in formato stampabile. Scegli la tua, stamparla o salvala sul telefono. Poi prendi il tuo calendario — adesso, non dopo — e segna i giorni di allenamento per le prossime 4 settimane. Un allenamento pianificato ha tre volte più probabilità di essere fatto rispetto a uno improvvisato. Nella prossima lezione parliamo del recupero.',
    },
  ],

  '3.4': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Il Recupero e la Rigenerazione Muscolare',
      sottotitolo: 'Perché riposare è parte dell\'allenamento, non il suo contrario',
      emoji: '😴',
      audioNarrazione: 'Questa è la lezione che molti saltano perché pensano che "riposare" sia per i pigri. In realtà è il contrario. I muscoli non crescono mentre ti alleni — crescono mentre recuperi. Senza recupero adeguato, ogni sessione è meno efficace della precedente.',
    },
    {
      id: 2,
      tipo: 'contenuto',
      titolo: 'Come Funziona la Crescita Muscolare',
      contenuto: 'L\'allenamento crea micro-lesioni muscolari. Il recupero le ripara, rendendo il muscolo più forte e grande. Questo processo richiede proteine adeguate, sonno di qualità e tempo. Senza uno dei tre, il processo si blocca.',
      emoji: '🔬',
      audioNarrazione: 'Quando ti alleni con i pesi, crei micro-lesioni nelle fibre muscolari. Il tuo corpo risponde riparando queste lesioni e rendendo il muscolo leggermente più forte e grande. Questo processo si chiama sintesi proteica muscolare e avviene principalmente durante il sonno. Richiede tre ingredienti: proteine sufficienti, sonno di qualità e tempo di recupero tra le sessioni.',
    },
    {
      id: 3,
      tipo: 'lista',
      titolo: 'I 4 Pilastri del Recupero',
      punti: [
        '😴 Sonno: 7-9 ore, la fase REM è fondamentale per la crescita',
        '🥗 Nutrizione: 20-40g proteine entro 2h dall\'allenamento',
        '💧 Idratazione: 2-3 litri al giorno (più con allenamento intenso)',
        '🧘 Gestione stress: il cortisolo alto blocca la crescita muscolare',
      ],
      audioNarrazione: 'I quattro pilastri del recupero. Il sonno: 7-9 ore a notte. Durante la fase REM il corpo produce l\'ormone della crescita che ripara i muscoli. La nutrizione post-allenamento: 20-40 grammi di proteine entro due ore dall\'allenamento. L\'idratazione: almeno 2-3 litri al giorno. Lo stress: il cortisolo alto blocca letteralmente la sintesi proteica. Meditazione, respirazione, natura — quello che funziona per te.',
    },
    {
      id: 4,
      tipo: 'contenuto',
      titolo: 'Tecniche di Recupero Attivo',
      contenuto: 'Il recupero attivo è più efficace del riposo totale. Nei giorni di pausa: camminata leggera 20-30 min, stretching o yoga, foam rolling, nuoto leggero o bici blanda.',
      emoji: '🚶',
      highlight: 'Muoversi piano recupera più velocemente che stare fermi',
      audioNarrazione: 'Il recupero attivo è più efficace del riposo totale. Nei giorni di pausa dall\'allenamento intenso, fai qualcosa di leggero: una camminata di 20-30 minuti, stretching o yoga, foam rolling sui muscoli dolenti, nuoto leggero o bici a bassa intensità. Il movimento leggero aumenta il flusso sanguigno nei muscoli, accelerando la rimozione dei metaboliti e portando nutrienti per la riparazione.',
    },
    {
      id: 5,
      tipo: 'lista',
      titolo: 'Segnali di Recupero Insufficiente',
      punti: [
        '😴 Stanchezza persistente nonostante il sonno',
        '📉 Performance in calo — sollevi meno di settimana scorsa',
        '😤 Irritabilità e umore basso',
        '🤕 Dolori muscolari che non passano dopo 48-72h',
        '🤒 Frequenti malattie — il sistema immunitario è stressato',
      ],
      audioNarrazione: 'Saper riconoscere il sovraffaticamento è fondamentale. I segnali sono: stanchezza che non passa nonostante il sonno. Performance in calo — sollevi meno o corri più lento rispetto alla settimana precedente. Irritabilità e umore basso senza motivo apparente. Dolori muscolari che durano più di 72 ore. E frequenti malattie: il sistema immunitario è stressato dall\'overtraining. Se hai tre o più di questi segnali, prenditi 3-4 giorni di recupero.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'Complimenti per il Modulo 3!',
      punti: [
        '✅ Hai scelto la tua scheda di allenamento',
        '✅ Sai combinare cardio, forza e flessibilità',
        '✅ Hai capito il recupero come parte attiva del progresso',
      ],
      highlight: 'Pronto per il Modulo 4: La Sfida dei 30 Giorni',
      audioNarrazione: 'Complimenti! Hai completato il Modulo 3. Ora hai un piano di allenamento completo e sai come recuperare al meglio. Nel Modulo 4 mettiamo tutto in pratica con la Sfida dei 30 Giorni: un programma step-by-step settimana per settimana per costruire abitudini solide. A presto!',
    },
  ],

  // ─────────────────────────────────────────────
  // MODULO 4 — La Sfida dei 30 Giorni
  // ─────────────────────────────────────────────

  '4.1': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'La Scienza delle Abitudini e della Costanza',
      sottotitolo: 'Perché 30 giorni cambiano il cervello',
      emoji: '🗓️',
      audioNarrazione: 'Benvenuto nel Modulo 4 — La Sfida dei 30 Giorni. Nei prossimi 30 giorni non stai solo cambiando il tuo corpo. Stai ricablando il tuo cervello. La neuroscienza è chiara: ci vogliono 21-66 giorni per automatizzare un comportamento. Questi 30 giorni sono il tuo punto di non ritorno.',
    },
    {
      id: 2,
      tipo: 'contenuto',
      titolo: 'Perché 30 Giorni Funzionano',
      contenuto: 'Le ricerche dell\'University College London mostrano che ci vogliono in media 66 giorni per formare un\'abitudine automatica. Ma i cambiamenti cerebrali iniziano dopo soli 21 giorni. I 30 giorni ti portano oltre il punto di resistenza massima.',
      emoji: '🧠',
      audioNarrazione: 'La ricerca della University College London, guidata dalla dottoressa Philippa Lally, ha dimostrato che le abitudini diventano automatiche in media dopo 66 giorni — non 21 come si credeva prima. Ma c\'è qualcosa di speciale nei 30 giorni: è il punto in cui la resistenza iniziale si abbassa, i risultati cominciano a essere visibili e il cervello inizia a richiedere il comportamento invece di resistere.',
    },
    {
      id: 3,
      tipo: 'lista',
      titolo: 'Il Loop dell\'Abitudine Fitness',
      punti: [
        '🔔 Segnale: orario fisso o evento trigger (es. alzarsi, uscire dal lavoro)',
        '🏃 Routine: l\'allenamento o la scelta alimentare',
        '🎁 Ricompensa: sensazione di completamento, endorfine, check sul tracker',
        '🔁 Ripetizione: il loop si rinforza ogni volta che si completa',
      ],
      audioNarrazione: 'Ricordi il loop dell\'abitudine dal Modulo 1? Nei 30 giorni questo loop si consolida. Il segnale diventa più potente — la sveglia delle 7 inizia ad attivare automaticamente la voglia di muoversi. La routine diventa più fluida — sai esattamente cosa fare. La ricompensa si interiorizza — non hai più bisogno di motivazione esterna perché il tuo corpo la richiede.',
    },
    {
      id: 4,
      tipo: 'contenuto',
      titolo: 'La Regola Più Importante: Mai Due Volte',
      contenuto: 'Saltare un allenamento non è un problema. Saltarne due di fila sì — è l\'inizio di una nuova abitudine, quella sbagliata. La ricerca mostra che dopo due giorni consecutivi di pausa, il loop deve essere riattivato quasi da zero.',
      emoji: '⚠️',
      highlight: 'Mai saltare due volte di fila — è la regola numero uno',
      audioNarrazione: 'La regola più importante di tutta la sfida è questa: mai saltare due volte di fila. Perdere un allenamento è normale, è umano, fa parte del percorso. Ma se salti due giorni consecutivi, il tuo cervello interpreta il segnale come "questa abitudine è finita" e deve ricominciare il processo di costruzione quasi da zero. Un giorno: incidente. Due giorni: nuova abitudine, quella sbagliata.',
    },
    {
      id: 5,
      tipo: 'lista',
      titolo: 'Il Tuo Sistema di Tracking',
      punti: [
        '📅 Calendario fisico: segna ogni giorno completato con una X',
        '📱 App: Habit tracking app o note sul telefono',
        '📊 Worksheet settimanale: punteggio da 1-10 per energia, umore, progressi',
        '📸 Foto mensile: stesso orario, stessa luce, stesso spazio',
      ],
      audioNarrazione: 'Il tracking dei progressi aumenta la probabilità di completare la sfida. Usa un calendario fisico e segna ogni giorno con una grande X rossa. La catena visiva di X consecutive è un potente motivatore — non vuoi spezzarla. Ogni settimana compila il worksheet con il punteggio da 1 a 10 su energia, umore, qualità del sonno e aderenza al piano. E una foto all\'inizio e alla fine di ogni mese.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'Sei Pronto per la Sfida',
      punti: [
        '✅ Hai capito la neuroscienza dei 30 giorni',
        '✅ Conosci il loop dell\'abitudine e come rafforzarlo',
        '✅ Hai il tuo sistema di tracking pronto',
        '✅ Ricordi la regola numero uno: mai due volte di fila',
      ],
      highlight: 'Nella prossima lezione: il piano settimane 1-2',
      audioNarrazione: 'Sei pronto. Nella prossima lezione ti dò il piano dettagliato settimana per settimana. Le prime due settimane costruiscono le fondamenta — sono le più difficili ma anche le più importanti. Vai forte!',
    },
  ],

  '4.2': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Settimane 1-2: Costruire le Fondamenta',
      sottotitolo: 'I 14 giorni più importanti del tuo percorso',
      emoji: '🏗️',
      audioNarrazione: 'Le prime due settimane sono le più difficili e le più importanti. Il corpo e la mente resistono al cambiamento. I muscoli sono doloranti. Le vecchie abitudini tirano forte. Ma è qui che si decide tutto. Chi supera le prime due settimane ha l\'80% di probabilità di completare i 30 giorni.',
    },
    {
      id: 2,
      tipo: 'lista',
      titolo: 'Il Piano Settimane 1-2',
      punti: [
        '🏋️ 3 sessioni di allenamento (20-30 min, intensità moderata)',
        '🚶 Camminata quotidiana 20-30 min (anche i giorni di riposo)',
        '🥗 Applica il piatto perfetto per almeno 5 pasti su 7 al giorno',
        '😴 Orario sonno fisso: stessa ora di andare a letto ogni sera',
        '💧 2 litri d\'acqua al giorno come minimo',
      ],
      audioNarrazione: 'Il piano per le prime due settimane è intenzionalmente semplice. Tre sessioni di allenamento brevi, 20-30 minuti, con intensità moderata — non devi distruggerti. Una camminata ogni giorno, anche di 20-30 minuti, anche nei giorni di riposo. Il piatto perfetto per almeno 5 pasti su 7. Un orario fisso per andare a letto. E 2 litri d\'acqua al giorno. Semplice? Sì. Facile? No. Ma fattibile.',
    },
    {
      id: 3,
      tipo: 'contenuto',
      titolo: 'L\'DOMS: Il Dolore Muscolare del Giorno Dopo',
      contenuto: 'Il dolore muscolare 24-48h dopo l\'allenamento (DOMS) è normale nelle prime settimane. Non indica danno — indica adattamento. Il movimento leggero lo riduce più del riposo totale.',
      emoji: '💪',
      audioNarrazione: 'Nelle prime settimane probabilmente sentirai il DOMS — Delayed Onset Muscle Soreness, il dolore muscolare che arriva 24-48 ore dopo l\'allenamento. È completamente normale e indica che il corpo si sta adattando. Non è un segnale di fermarsi — è un segnale di progresso. La cosa migliore per il DOMS non è il riposo totale ma il movimento leggero: camminata, stretching, nuoto blando.',
    },
    {
      id: 4,
      tipo: 'lista',
      titolo: 'Le 3 Priorità di Ogni Giorno',
      punti: [
        '1️⃣ Movimento: allenamento o camminata (senza eccezioni)',
        '2️⃣ Proteine: raggiungi il tuo obiettivo proteico giornaliero',
        '3️⃣ Sonno: vai a letto all\'orario stabilito',
      ],
      audioNarrazione: 'In ogni giornata hai tre priorità e solo tre. Primo: il movimento — allenamento o almeno una camminata, senza eccezioni. Secondo: le proteine — raggiungi il tuo obiettivo proteico, anche se il resto della dieta non è perfetto. Terzo: il sonno — rispetta l\'orario di andare a letto. Se riesci a fare queste tre cose ogni giorno, dopo 14 giorni sarai già una persona diversa.',
    },
    {
      id: 5,
      tipo: 'contenuto',
      titolo: 'La Crisi del Giorno 3-5',
      contenuto: 'Quasi tutti vivono una crisi tra il giorno 3 e il giorno 5: stanchezza, dubbi, voglia di mollare. Questo è normale — è il vecchio cervello che difende le sue abitudini. Supera questi giorni e il peggio è passato.',
      emoji: '⛰️',
      highlight: 'La crisi del giorno 3-5 è normale — non mollare ora',
      audioNarrazione: 'C\'è un pattern universale nella sfida dei 30 giorni. I giorni 1-2 sono carichi di entusiasmo. Poi arriva la crisi tra il giorno 3 e il 5: stanchezza, muscoli doloranti, dubbi, voglia di rimandare. Questo è il vecchio cervello che difende le sue abitudini consolidate. È normale, succede a quasi tutti. Ma se superi questi giorni, il percorso diventa progressivamente più facile.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'Il Tuo Piano per le Prime 2 Settimane',
      punti: [
        '✅ 3 sessioni allenamento + camminata quotidiana',
        '✅ Piatto perfetto 5/7 pasti',
        '✅ Sonno a orario fisso + 2L acqua',
        '✅ Supera la crisi del giorno 3-5 senza cedere',
      ],
      highlight: 'Nella prossima lezione: settimane 3-4, consolida e intensifica',
      audioNarrazione: 'Hai il piano per le prime due settimane. È semplice, è fattibile, è sufficiente. Non cercare di fare troppo subito. Costruisci le fondamenta. Nella prossima lezione vedremo come intensificare il tutto nelle settimane 3 e 4, quando il corpo è pronto per lo step successivo.',
    },
  ],

  '4.3': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Settimane 3-4: Consolidare e Intensificare',
      sottotitolo: 'Hai superato il momento difficile — ora acceleri',
      emoji: '🚀',
      audioNarrazione: 'Sei arrivato alle settimane 3 e 4. Le abitudini iniziano a essere più automatiche, il dolore muscolare è diminuito, e inizi a vedere qualche risultato. È il momento di alzare l\'asticella. Non troppo, ma abbastanza da creare un nuovo stimolo.',
    },
    {
      id: 2,
      tipo: 'lista',
      titolo: 'Il Piano Settimane 3-4',
      punti: [
        '🏋️ 4 sessioni di allenamento (30-45 min, intensità più alta)',
        '🚶 8.000-10.000 passi al giorno come obiettivo minimo',
        '🥗 Piatto perfetto 6/7 pasti — solo un pasto libero a settimana',
        '😴 Ottimizza il sonno: buio totale, niente telefono 30 min prima',
        '📊 Misura e registra i tuoi progressi',
      ],
      audioNarrazione: 'Nelle settimane 3 e 4 alzi il volume. Quattro sessioni di allenamento di 30-45 minuti con intensità maggiore. 8-10 mila passi al giorno come baseline. Il piatto perfetto per 6 pasti su 7 — mantieni un solo pasto libero. Ottimizza il sonno con buio totale e niente telefono nei 30 minuti prima di dormire. E inizia a misurare i tuoi progressi in modo sistematico.',
    },
    {
      id: 3,
      tipo: 'contenuto',
      titolo: 'Come Misurare i Progressi nel Modo Giusto',
      contenuto: 'La bilancia è solo uno dei 5 indicatori. Misura anche: misurazioni corporee (vita, fianchi, braccia), foto comparative, performance in palestra, livello di energia e qualità del sonno.',
      emoji: '📏',
      audioNarrazione: 'Uno degli errori più comuni è misurare i progressi solo con la bilancia. Il peso può rimanere stabile mentre il corpo cambia completamente composizione: perdi grasso e guadagni muscolo. Gli indicatori migliori sono cinque: le misurazioni corporee — vita, fianchi, braccia. Le foto comparative. La performance in palestra — sollevi di più? Corri più veloce? Il livello di energia durante il giorno. E la qualità del sonno.',
    },
    {
      id: 4,
      tipo: 'lista',
      titolo: 'La Progressione degli Esercizi',
      punti: [
        '⬆️ Aumenta il carico di 2-5% quando esegui tutte le rip con buona forma',
        '🔄 Aggiungi 1 serie per esercizio rispetto alle settimane 1-2',
        '⏱️ Riduci i tempi di recupero tra le serie (da 90 a 60 secondi)',
        '🆕 Sostituisci 1-2 esercizi con varianti più difficili',
      ],
      audioNarrazione: 'La progressione è obbligatoria — senza di essa il corpo smette di adattarsi. Nelle settimane 3-4 fai così: aumenta il carico del 2-5% quando riesci a completare tutte le ripetizioni con tecnica impeccabile. Aggiungi una serie per esercizio. Riduci i tempi di recupero tra le serie da 90 a 60 secondi. E sostituisci uno o due esercizi con varianti più difficili.',
    },
    {
      id: 5,
      tipo: 'citazione',
      titolo: '',
      citazione: 'Non devi essere bravo per iniziare, ma devi iniziare per essere bravo.',
      autore: 'Zig Ziglar',
      audioNarrazione: 'Zig Ziglar diceva: non devi essere bravo per iniziare, ma devi iniziare per essere bravo. Sei già alla settimana 3. Hai già iniziato. Ora continua. La consistenza batte la perfezione, sempre.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'Stai Diventando la Versione Migliore di Te',
      punti: [
        '✅ 4 sessioni/sett con intensità crescente',
        '✅ 8-10k passi al giorno',
        '✅ Misuri i progressi con 5 indicatori',
        '✅ Progressione sistematica negli esercizi',
      ],
      highlight: 'Nella prossima lezione: come gestire le crisi e ripartire dopo un fallimento',
      audioNarrazione: 'Sei sulla buona strada. Le settimane 3-4 sono dove avviene la vera trasformazione. Il corpo si adatta, la mente si calma, le abitudini diventano automatiche. Nella prossima lezione ti insegno a gestire le crisi — perché arriveranno — e come ripartire dopo un fallimento senza perdere tutto.',
    },
  ],

  '4.4': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Superare le Crisi, i Fallimenti e Ripartire',
      sottotitolo: 'Non se cadrai — ma quando. E come rialzarsi in fretta',
      emoji: '💥',
      audioNarrazione: 'Questa lezione non è se cadrai nel corso dei 30 giorni. È quando. Perché tutti cadono. La differenza tra chi raggiunge l\'obiettivo e chi no non è non cadere mai — è rialzarsi velocemente. Oggi ti do gli strumenti per farlo.',
    },
    {
      id: 2,
      tipo: 'lista',
      titolo: 'Le 5 Crisi Più Comuni nei 30 Giorni',
      punti: [
        '😤 Settimana 1: dolori muscolari e demotivazione iniziale',
        '😔 Giorno 8-10: il "che senso ha" — risultati non ancora visibili',
        '🤒 Malattia improvvisa: come non perdere tutto il lavoro fatto',
        '🎉 Evento sociale: cena di lavoro, compleanno, vacanza',
        '😩 Settimana 3-4: plateau — il corpo rallenta i progressi',
      ],
      audioNarrazione: 'Le cinque crisi più comuni. La prima settimana: dolori muscolari e "perché lo sto facendo". Il giorno 8-10: il momento "che senso ha" quando i risultati non si vedono ancora. La malattia improvvisa. L\'evento sociale che scompagina tutto. E il plateau delle settimane 3-4 quando i progressi rallentano. Per ognuna di queste hai un protocollo specifico.',
    },
    {
      id: 3,
      tipo: 'lista',
      titolo: 'Il Protocollo di Ripartenza',
      punti: [
        '1️⃣ Accetta senza giudicarti: è successo, non cambia',
        '2️⃣ Identifica cosa ha causato la crisi (segnale, situazione)',
        '3️⃣ Riparti dal passo successivo, non dall\'inizio',
        '4️⃣ Riduci temporaneamente il volume (piano minimo)',
        '5️⃣ Torna al piano completo dopo 2-3 giorni',
      ],
      audioNarrazione: 'Ecco il protocollo in cinque passi. Primo: accetta senza giudicarti — è successo, non puoi cambiarlo. Secondo: identifica cosa lo ha causato per evitarlo la prossima volta. Terzo: riparti dal passo successivo, non dall\'inizio — non riazzerare tutto. Quarto: attiva il piano minimo per 2-3 giorni — anche solo una camminata conta. Quinto: torna al piano completo dopo la mini-transizione.',
    },
    {
      id: 4,
      tipo: 'contenuto',
      titolo: 'Il Piano Minimo di Emergenza',
      contenuto: 'Quando tutto crolla, esegui il piano minimo: 20 minuti di camminata + 25-30g di proteine ad ogni pasto + 7 ore di sonno. Questo mantiene l\'inerzia senza stressarti.',
      emoji: '🆘',
      highlight: '20 min camminata + proteine + sonno = mai perdere l\'abitudine',
      audioNarrazione: 'Il piano minimo di emergenza è la tua rete di sicurezza. Quando sei malato, stressato, in viaggio, quando la vita è caotica — esegui questo e solo questo. 20 minuti di camminata. 25-30 grammi di proteine ad ogni pasto. 7 ore di sonno. Nient\'altro. Questo mantiene l\'inerzia dell\'abitudine senza aggiungere stress in un momento già difficile.',
    },
    {
      id: 5,
      tipo: 'citazione',
      titolo: '',
      citazione: 'Il successo non è finale, il fallimento non è fatale: è il coraggio di continuare che conta.',
      autore: 'Winston Churchill',
      audioNarrazione: 'Winston Churchill lo ha detto meglio di chiunque altro: il successo non è finale, il fallimento non è fatale. È il coraggio di continuare che conta. Un fallimento non cancella 20 giorni di lavoro duro. Continua.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'Hai Completato la Sfida dei 30 Giorni!',
      punti: [
        '✅ Conosci le 5 crisi più comuni e come gestirle',
        '✅ Hai il protocollo di ripartenza in 5 passi',
        '✅ Il piano minimo è la tua rete di sicurezza',
        '✅ Sei diventato qualcuno che non molla',
      ],
      highlight: 'Pronto per il Modulo 5: Strumenti, Monitoraggio e Futuro',
      audioNarrazione: 'Hai completato il Modulo 4 sulla Sfida dei 30 Giorni. Ora sai come costruire, mantenere e rilanciare le tue abitudini anche nelle situazioni difficili. Nel Modulo 5 — l\'ultimo — scoprirai gli strumenti digitali per monitorare i progressi, come mantenere i risultati a lungo termine, e costruirai il tuo piano personale per i prossimi 90 giorni. Ci vediamo lì!',
    },
  ],

  // ─────────────────────────────────────────────
  // MODULO 5 — Strumenti, Monitoraggio e Futuro
  // ─────────────────────────────────────────────

  '5.1': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Strumenti Digitali e App per il Fitness',
      sottotitolo: 'Le app e i device che moltiplicano i tuoi risultati',
      emoji: '📱',
      audioNarrazione: 'Benvenuto nell\'ultimo modulo. Oggi parliamo di strumenti digitali: app, wearable e tecnologie che possono moltiplicare i tuoi risultati — se usati correttamente. Perché la tecnologia da sola non cambia nulla. Ma la tecnologia giusta + il tuo impegno è una combinazione imbattibile.',
    },
    {
      id: 2,
      tipo: 'lista',
      titolo: 'Le Migliori App per il Tracking Nutrizionale',
      punti: [
        '🥗 MyFitnessPal — database enorme, facile da usare, free',
        '🇮🇹 Yazio — ottimo per l\'italiano, database cibi italiani',
        '🔬 Cronometer — il più preciso per micronutrienti',
        '📊 Tutti e tre: scansiona il barcode, traccia i macro in tempo reale',
      ],
      audioNarrazione: 'Per il tracking nutrizionale hai tre opzioni eccellenti. MyFitnessPal: il più diffuso al mondo, database enorme, interfaccia semplice, versione gratuita molto completa. Yazio: ottimo database di cibi italiani — pasta, formaggi, salumi — molto più preciso per noi. Cronometer: il più dettagliato per chi vuole monitorare anche i micronutrienti come vitamine e minerali. Tutti e tre permettono di scansionare il barcode dei prodotti.',
    },
    {
      id: 3,
      tipo: 'lista',
      titolo: 'Le Migliori App per l\'Allenamento',
      punti: [
        '💪 Strong — log degli allenamenti con grafici progressione (la migliore)',
        '🏃 Nike Training Club — video allenamenti guidati, free',
        '🚴 Strava — running e ciclismo, community motivante',
        '🧘 Down Dog — yoga e stretching adattivo',
      ],
      audioNarrazione: 'Per l\'allenamento: Strong è la migliore app per il log dei pesi — traccia ogni serie, ripetizione e carico, con grafici di progressione chiarissimi. Nike Training Club offre centinaia di allenamenti video gratuiti per ogni livello. Strava è perfetta per running e ciclismo con la componente social che motiva. Down Dog per yoga e stretching adattivi al tuo livello.',
    },
    {
      id: 4,
      tipo: 'lista',
      titolo: 'Wearable: Vale la Pena Investire?',
      punti: [
        '⌚ Apple Watch / Garmin: passi, frequenza cardiaca, calorie (utili)',
        '💍 Oura Ring: il miglior tracker per il sonno (altamente consigliato)',
        '⚖️ Bilancia smart: peso + massa grassa + idratazione (con cautela)',
        '💡 Regola: usa solo quello che guardi davvero ogni giorno',
      ],
      audioNarrazione: 'I wearable valgono l\'investimento se li usi davvero. Apple Watch e Garmin sono ottimi per monitorare passi, frequenza cardiaca durante l\'allenamento e stima delle calorie bruciate. L\'Oura Ring è il migliore per il monitoraggio del sonno — ti dà un punteggio di prontezza ogni mattina che aiuta a decidere se spingere o recuperare. La regola d\'oro: acquista solo quello che sai che userai ogni giorno.',
    },
    {
      id: 5,
      tipo: 'contenuto',
      titolo: 'Il Pericolo della Paralisi da Analisi',
      contenuto: 'Troppi dati possono essere peggio di nessun dato. Scegli 2-3 metriche da monitorare e ignorare il resto. Il tuo corpo non è un grafico Excel — è un sistema biologico complesso.',
      emoji: '⚠️',
      highlight: 'Monitora 2-3 metriche, non tutto',
      audioNarrazione: 'Attenzione al rischio opposto: la paralisi da analisi. Monitorare tutto — calorie, macro, passi, sonno, variabilità cardiaca, peso, misurazioni — può diventare ossessivo e controproducente. Scegli due o tre metriche che sono significative per il tuo obiettivo e monitorale con costanza. Ignora il resto. Il tuo corpo risponde all\'allenamento e al cibo, non ai tuoi grafici.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'Il Tuo Stack Tecnologico',
      punti: [
        '✅ 1 app nutrizionale: MyFitnessPal, Yazio o Cronometer',
        '✅ 1 app allenamento: Strong o Nike Training Club',
        '✅ Opzionale: wearable per sonno e attività',
        '✅ Monitora 2-3 metriche, non tutto',
      ],
      highlight: 'Nella prossima lezione: come misurare i progressi nel modo corretto',
      audioNarrazione: 'Nella prossima lezione entriamo nel dettaglio su come misurare i progressi nel modo corretto — non solo con la bilancia. Scoprirai i 5 indicatori che contano davvero e come usarli per aggiustare il piano quando necessario.',
    },
  ],

  '5.2': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Come Misurare e Monitorare i Progressi',
      sottotitolo: 'I 5 indicatori che mostrano davvero se stai migliorando',
      emoji: '📊',
      audioNarrazione: 'Misurare correttamente i progressi è un\'arte. La bilancia è l\'indicatore più ingannevole che esista — eppure è quello che tutti guardano. Oggi ti mostro i cinque indicatori che contano davvero e come usarli per ottimizzare il tuo piano.',
    },
    {
      id: 2,
      tipo: 'lista',
      titolo: 'I 5 Indicatori che Contano',
      punti: [
        '📏 Misurazioni corporee (vita, fianchi, braccia, cosce)',
        '📸 Foto comparative (ogni 4 settimane, stesso orario)',
        '💪 Performance: carichi, distanze, tempi migliorati',
        '⚡ Energia soggettiva (scala 1-10 al mattino)',
        '😴 Qualità del sonno (ore, risvegli, punteggio Oura)',
      ],
      audioNarrazione: 'I cinque indicatori che contano. Primo: le misurazioni corporee con il metro da sarto — vita, fianchi, braccia, cosce. Da fare ogni due settimane al mattino a digiuno. Secondo: le foto comparative ogni 4 settimane, stesso orario, stessa luce, stesso spazio. Terzo: la performance in palestra — sollevi di più? Corri più veloce? Questi sono progressi oggettivi. Quarto: l\'energia soggettiva — quanto ti senti bene al mattino su scala da 1 a 10. Quinto: la qualità del sonno.',
    },
    {
      id: 3,
      tipo: 'contenuto',
      titolo: 'La Bilancia: Come Usarla Senza Farsi del Male',
      contenuto: 'Il peso oscilla di 1-2 kg ogni giorno per acqua, cibo nello stomaco, ciclo ormonale. Guarda la media settimanale, non il dato giornaliero. Pesati ogni mattina a digiuno, calcola la media di 7 giorni.',
      emoji: '⚖️',
      audioNarrazione: 'Se vuoi usare la bilancia, fallo in modo intelligente. Il peso può oscillare da 1 a 2 kg nella stessa giornata: dopo una cena salata, prima e dopo la palestra, durante il ciclo mestruale. Il dato singolo non significa nulla. Quello che conta è la media settimanale. Pesati ogni mattina a digiuno dopo essere andato in bagno, registra il numero, e calcola la media dei 7 giorni. Solo la tendenza della media settimanale è significativa.',
    },
    {
      id: 4,
      tipo: 'contenuto',
      titolo: 'Come Leggere un Plateau',
      contenuto: 'Un plateau non è fallimento — è adattamento. Il corpo è diventato più efficiente. Soluzioni: aumenta il deficit di 100-200 kcal, aggiungi 1 sessione di cardio, cambia gli esercizi, fai una settimana di refeed.',
      emoji: '📉',
      highlight: 'Plateau = adattamento. Adatta il piano, non arrenderti',
      audioNarrazione: 'Quando i progressi si fermano, la maggior parte delle persone pensa di aver fallito. In realtà è il contrario: il corpo si è adattato, è diventato più efficiente. È un segnale di miglioramento, non di fallimento. Le soluzioni sono quattro. Prima: riduci le calorie di 100-200 al giorno. Seconda: aggiungi una sessione di cardio. Terza: cambia gli esercizi per un nuovo stimolo. Quarta: fai una settimana di refeed — mangi a mantenimento per riattivare il metabolismo.',
    },
    {
      id: 5,
      tipo: 'lista',
      titolo: 'Il Check-Up Mensile',
      punti: [
        '📅 Ogni 4 settimane: foto + misurazioni + peso medio',
        '💪 Aggiorna il record personale di ogni esercizio chiave',
        '📋 Rivedi il piano: cosa sta funzionando, cosa cambiare',
        '🎯 Aggiorna l\'obiettivo se necessario (più vicino, più ambizioso)',
      ],
      audioNarrazione: 'Il check-up mensile è il tuo momento di revisione strategica. Ogni 4 settimane dedica 30 minuti a fare le foto, misurazioni e peso medio. Aggiorna i record personali di squat, panca, corsa. Rivedi il piano: cosa ha funzionato bene, cosa ha creato attrito. E aggiorna l\'obiettivo — magari l\'hai già raggiunto e puoi puntare più in alto, o magari hai bisogno di aggiustarlo.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'Monitorare = Migliorare',
      punti: [
        '✅ Usa i 5 indicatori, non solo la bilancia',
        '✅ Guarda la media settimanale del peso',
        '✅ Un plateau è adattamento: hai 4 soluzioni',
        '✅ Check-up mensile per rivedere e aggiornare il piano',
      ],
      highlight: 'Nella prossima lezione: come mantenere i risultati per sempre',
      audioNarrazione: 'Ottimo. Ora sai come misurare i progressi nel modo corretto. Nella prossima lezione — la penultima — affrontiamo la domanda che tutti si fanno: come fare per mantenere i risultati a lungo termine senza tornare al punto di partenza.',
    },
  ],

  '5.3': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Mantenere i Risultati nel Lungo Termine',
      sottotitolo: 'Il vero obiettivo non è arrivarci — è restare',
      emoji: '🏆',
      audioNarrazione: 'Questa è una delle lezioni più importanti del corso. Moltissime persone raggiungono il loro obiettivo ma poi, in 6-12 mesi, ritornano al punto di partenza. Non perché non abbiano forza di volontà, ma perché non hanno una strategia di mantenimento. Oggi costruiamo la tua.',
    },
    {
      id: 2,
      tipo: 'contenuto',
      titolo: 'La Trappola del "Obiettivo Raggiunto"',
      contenuto: 'Il cervello interpreta il raggiungimento dell\'obiettivo come "missione compiuta" e rilassa le abitudini. Soluzione: non avere un obiettivo finale, ma un\'identità permanente. Non "voglio pesare 70 kg" ma "sono una persona attiva e sana".',
      emoji: '⚠️',
      audioNarrazione: 'La ricerca sul comportamento mostra che il raggiungimento di un obiettivo spesso innesca un rilassamento delle abitudini. Il cervello registra "missione compiuta" e torna alle routine precedenti. La soluzione è spostare l\'identità dall\'obiettivo al processo. Non "voglio perdere 10 kg" ma "sono una persona che si muove ogni giorno e mangia bene". Quando l\'identità cambia, il comportamento segue automaticamente.',
    },
    {
      id: 3,
      tipo: 'lista',
      titolo: 'Il Minimo Mantenimento',
      punti: [
        '💪 2 sessioni di forza a settimana (irrinunciabili)',
        '🚶 30 minuti di camminata quotidiana',
        '🥗 Proteine adeguate ad ogni pasto',
        '😴 7-8 ore di sonno',
        '🔄 Una revisione mensile dei progressi',
      ],
      highlight: 'Il minimo mantenimento è non negoziabile',
      audioNarrazione: 'Il minimo mantenimento è il tuo contratto con te stesso per i risultati a lungo termine. Non negoziabile. Due sessioni di forza a settimana — anche di 30 minuti. Una camminata di almeno 30 minuti ogni giorno — puoi spezzarla in due. Proteine adeguate ad ogni pasto — il singolo fattore più importante. Sette o otto ore di sonno. E una revisione mensile dei progressi. Con questi cinque elementi manterrai l\'80% dei tuoi risultati anche nelle fasi di vita più intense.',
    },
    {
      id: 4,
      tipo: 'contenuto',
      titolo: 'Come Gestire le Fasi di Vita Difficile',
      contenuto: 'Lavoro intenso, traslochi, figli piccoli, lutti — la vita interrompe i piani migliori. Strategia: attiva il piano minimo, non abbandonare tutto. Il 20% è infinitamente meglio dello 0%.',
      emoji: '🌊',
      audioNarrazione: 'La vita reale è fatta di fasi difficili: un lavoro nuovo molto intenso, un bambino che non dorme, un trasloco, un lutto. In questi momenti il perfezionismo è il tuo peggior nemico. Se non puoi fare tutto, fai il minimo. Venti per cento è infinitamente meglio di zero. Una camminata di 15 minuti è meglio di nessuna sessione. Un pasto proteico è meglio di saltare il pasto. L\'abitudine si mantiene anche a bassa intensità.',
    },
    {
      id: 5,
      tipo: 'lista',
      titolo: 'Il Sistema di "Reset" Stagionale',
      punti: [
        '🌱 Ogni 3 mesi: rivedi obiettivi e aggiorna il piano',
        '📈 Alterna fasi di intensificazione e fasi di mantenimento',
        '🎯 Ogni anno: scegli un nuovo obiettivo fitness (gara, evento, sfida)',
        '👥 Connettiti con una community o un partner di allenamento',
      ],
      audioNarrazione: 'Il sistema di reset stagionale ti mantiene motivato nel lungo periodo. Ogni tre mesi rivedi il piano e aggiorna gli obiettivi. Alterna fasi di intensificazione — dove spingi di più — a fasi di mantenimento. Ogni anno scegli un nuovo obiettivo sfidante: una gara di 10 km, una sfida di trazioni, un corso di arti marziali. La novità mantiene il cervello ingaggiato. E connettiti con una community: le persone che si allenano insieme ottengono risultati migliori e li mantengono più a lungo.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'I Risultati Sono Tuoi Per Sempre',
      punti: [
        '✅ Sposta l\'identità dall\'obiettivo al processo',
        '✅ Il minimo mantenimento è il tuo contratto con te stesso',
        '✅ Nelle fasi difficili: 20% batte sempre 0%',
        '✅ Reset stagionale ogni 3 mesi per restare motivato',
      ],
      highlight: 'Ultima lezione: il tuo piano personale per i prossimi 90 giorni',
      audioNarrazione: 'Nella prossima lezione — l\'ultima del corso — costruiamo insieme il tuo piano personale per i prossimi 90 giorni. Usando il metodo OKR, trasformeremo tutto quello che hai imparato in un piano d\'azione concreto. Ci vediamo per il gran finale!',
    },
  ],

  '5.4': [
    {
      id: 1,
      tipo: 'intro',
      titolo: 'Il Tuo Prossimo Capitolo: Piano a 90 Giorni',
      sottotitolo: 'Trasformi tutto quello che hai imparato in un piano d\'azione',
      emoji: '🗺️',
      audioNarrazione: 'Questa è l\'ultima lezione del corso Torno in Forma. Non un punto finale, ma un punto di partenza. Oggi costruisci il tuo piano personale per i prossimi 90 giorni usando il metodo OKR. Quello che costruisci qui sarà il blueprint del tuo futuro fisico.',
    },
    {
      id: 2,
      tipo: 'contenuto',
      titolo: 'Il Metodo OKR per il Fitness',
      contenuto: 'OKR (Objectives and Key Results) è il sistema usato da Google e dalle startup di successo per fissare obiettivi. Funziona perfettamente per il fitness: un Obiettivo ispirazionale + 3-4 Risultati Chiave misurabili.',
      emoji: '🎯',
      audioNarrazione: 'Il metodo OKR, usato da Google, Intel e dalle migliori aziende al mondo, funziona perfettamente per il fitness. Hai un Obiettivo: qualcosa di ispirazionale, ambizioso, che ti entusiasma. E hai tre o quattro Risultati Chiave: metriche concrete e misurabili che indicano se stai raggiungendo l\'obiettivo. Esempio: Obiettivo "Essere la versione più sana di me". Risultati chiave: correre 5 km senza fermarsi, mantenere 80 kg per 30 giorni, dormire 7+ ore per 25 giorni su 30.',
    },
    {
      id: 3,
      tipo: 'esercizio',
      titolo: 'Costruisci il Tuo OKR a 90 Giorni',
      contenuto: 'Nel worksheet scrivi:\n1. Il tuo Obiettivo a 90 giorni (ispirazionale)\n2. 3-4 Risultati Chiave con numero e data\n3. Le azioni settimanali per raggiungere ogni KR\n4. Il tuo sistema di tracking',
      emoji: '✍️',
      audioNarrazione: 'Apri il worksheet dell\'ultima lezione. Prima scrivi il tuo obiettivo a 90 giorni — deve essere ispirazionale, deve farti sentire qualcosa. Poi scrivi tre o quattro risultati chiave con numeri precisi e date. Poi per ogni risultato chiave scrivi le azioni settimanali concrete. Infine definisci il tuo sistema di tracking: come e quando misurerai i progressi ogni settimana.',
    },
    {
      id: 4,
      tipo: 'lista',
      titolo: 'Le 4 Abitudini Anchor per il Futuro',
      punti: [
        '🏋️ Allenamento di forza: 2-3 volte a settimana — sempre',
        '🚶 Camminata: 30 minuti al giorno — sempre',
        '🥗 Proteine: ad ogni pasto, sempre — non trattabile',
        '😴 Sonno: 7+ ore, orario fisso — la base di tutto il resto',
      ],
      audioNarrazione: 'Ci sono quattro abitudini anchor — ancoranti — che sono la base di qualsiasi piano fitness a lungo termine. L\'allenamento di forza due o tre volte a settimana: non negoziabile. La camminata di trenta minuti al giorno: anche spezzata, anche al telefono, anche con il cane. Le proteine ad ogni pasto: il singolo fattore nutrizionale più importante per la composizione corporea. Il sonno di sette ore minimo: tutto il resto — allenamento, alimentazione, stress — migliora con il sonno.',
    },
    {
      id: 5,
      tipo: 'citazione',
      titolo: '',
      citazione: 'Tra un anno desidererai di aver iniziato oggi.',
      autore: 'Karen Lamb',
      audioNarrazione: 'Karen Lamb lo ha scritto decenni fa, ma è più vero che mai: tra un anno desidererai di aver iniziato oggi. Tu hai iniziato. Hai completato questo corso. Ora hai gli strumenti, il piano, e — soprattutto — sai che ce la fai.',
    },
    {
      id: 6,
      tipo: 'riepilogo',
      titolo: 'Congratulazioni! Hai Completato il Corso',
      punti: [
        '🏆 Hai completato i 5 moduli del corso Torno in Forma',
        '✅ Hai un piano a 90 giorni con metodo OKR',
        '✅ Conosci le 4 abitudini anchor per il futuro',
        '📞 Andrea è disponibile per un check-in mensile',
      ],
      highlight: 'Questo non è un punto finale. È il tuo nuovo punto di partenza.',
      audioNarrazione: 'Congratulazioni. Hai completato il corso Torno in Forma. Hai imparato la scienza della motivazione, la nutrizione applicata, il piano di allenamento personalizzato, la sfida dei 30 giorni e gli strumenti per il monitoraggio. Soprattutto hai un piano d\'azione concreto per i prossimi 90 giorni. Questo non è un punto finale. È il tuo nuovo punto di partenza. Vai forte. Andrea.',
    },
  ],
}
